import doggo from "../assets/dogIcons/Doggo__00.png";
import pic01 from "../assets/dogIcons/Picture__01.png";
import pic02 from "../assets/dogIcons/Picture__02.png";
import pic03 from "../assets/dogIcons/Picture__03.png";
import pic04 from "../assets/dogIcons/Picture__04.png";
import pic05 from "../assets/dogIcons/Picture__05.png";
import pic06 from "../assets/dogIcons/Picture__06.png";
import pic07 from "../assets/dogIcons/Picture__07.png";
import pic08 from "../assets/dogIcons/Picture__08.png";
import pic09 from "../assets/dogIcons/Picture__09.png";
import pic10 from "../assets/dogIcons/Picture__10.png";
import pic11 from "../assets/dogIcons/Picture__11.png";
import pic12 from "../assets/dogIcons/Picture__12.png";
import pic13 from "../assets/dogIcons/Picture__13.png";
import pic14 from "../assets/dogIcons/Picture__14.png";
import pic15 from "../assets/dogIcons/Picture__15.png";
import pic16 from "../assets/dogIcons/Picture__16.png";
import pic17 from "../assets/dogIcons/Picture__17.png";
import pic18 from "../assets/dogIcons/Picture__18.png";
import pic19 from "../assets/dogIcons/Picture__19.png";
import pic20 from "../assets/dogIcons/Picture__20.png";

const INITIALGRID = [
  {
    id: "row00",
    cellArray: [
      {
        id: "label-00",
        cellText: "Label00",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-00",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-01",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-02",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-03",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-04",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-05",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-06",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-07",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-08",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
      {
        id: "target-09",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer0",
        },
      },
    ],
  },
  {
    id: "row01",
    cellArray: [
      {
        id: "label-01",
        cellText: "Label01",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-10",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-11",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-12",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-13",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-14",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-15",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-16",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-17",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-18",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
      {
        id: "target-19",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer1",
        },
      },
    ],
  },
  {
    id: "row02",
    cellArray: [
      {
        id: "label-20",
        cellText: "Label02",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-20",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-21",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-22",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-23",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-24",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-25",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-26",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-27",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-28",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
      {
        id: "target-29",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer2",
        },
      },
    ],
  },
  {
    id: "row03",
    cellArray: [
      {
        id: "label-30",
        cellText: "Label03",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-30",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-31",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-32",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-33",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-34",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-35",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-36",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-37",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-38",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
      {
        id: "target-39",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer3",
        },
      },
    ],
  },
  {
    id: "row04",
    cellArray: [
      {
        id: "label-40",
        cellText: "Label04",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-40",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-41",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-42",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-43",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-44",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-45",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-46",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-47",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-48",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
      {
        id: "target-49",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer4",
        },
      },
    ],
  },
  {
    id: "row05",
    cellArray: [
      {
        id: "label-50",
        cellText: "Label05",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-50",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-51",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-52",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-53",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-54",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-55",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-56",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-57",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-58",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
      {
        id: "target-59",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer5",
        },
      },
    ],
  },
  {
    id: "row06",
    cellArray: [
      {
        id: "label-60",
        cellText: "Label06",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-60",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-61",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-62",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-63",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-64",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-65",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-66",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-67",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-68",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
      {
        id: "target-69",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer6",
        },
      },
    ],
  },
  {
    id: "row07",
    cellArray: [
      {
        id: "label-70",
        cellText: "Label07",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-70",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-71",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-72",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-73",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-74",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-75",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-76",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-77",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-78",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
      {
        id: "target-79",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer7",
        },
      },
    ],
  },
  {
    id: "row08",
    cellArray: [
      {
        id: "label-80",
        cellText: "Label08",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-80",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-81",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-82",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-83",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-84",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-85",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-86",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-87",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-88",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
      {
        id: "target-89",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer8",
        },
      },
    ],
  },
  {
    id: "row09",
    cellArray: [
      {
        id: "label-09",
        cellText: "Label09",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-90",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: "",
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-91",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-92",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-93",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-94",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-95",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-96",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-97",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-98",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
      {
        id: "target-99",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBox",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "parentContainer9",
        },
      },
    ],
  },
  {
    id: "row10",
    cellArray: [
      {
        id: "labe-l0",
        cellText: "Label10",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBoxP",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-100",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__01.png",
          imageString: pic01,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-100",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-101",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__02.png",
          imageString: pic02,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-101",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-102",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__03.png",
          imageString: pic03,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-102",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-103",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__04.png",
          imageString: pic04,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-103",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-104",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__05.png",
          imageString: pic05,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-104",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-105",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__06.png",
          imageString: pic06,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-105",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-106",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__07.png",
          imageString: pic07,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-106",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-107",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__08.png",
          imageString: pic08,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-107",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-108",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__09.png",
          imageString: pic09,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-108",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
      {
        id: "target-109",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__10.png",
          imageString: pic10,
          imageUrl: "img/FrenchBulldog1.png",
          currentImgDivId: "target-109",
          dropImgLoc: "",
          dropImgParent: "parentContainer10",
        },
      },
    ],
  },
  {
    id: "row11",
    cellArray: [
      {
        id: "label-11",
        cellText: "Label11",
        cellLocation: "item-label-cell0",
        cellStyle: "myLabelBoxP",
        image: {
          type: "",
          draggable: false,
          imageId: "",
          imageUrl: "",
          currentImgLoc: "",
          dropImgLoc: "",
          dropImgParent: "",
        },
      },
      {
        id: "target-110",
        cellText: "",
        cellLocation: "item-image-cell0",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__11.png",
          imageString: pic11,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-110",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-111",
        cellText: "",
        cellLocation: "item-image-cell1",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__12.png",
          imageString: pic12,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-111",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-112",
        cellText: "",
        cellLocation: "item-image-cell2",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__13.png",
          imageString: pic13,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-112",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-113",
        cellText: "",
        cellLocation: "item-image-cell3",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__14.png",
          imageString: pic14,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-113",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-114",
        cellText: "",
        cellLocation: "item-image-cell4",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__15.png",
          imageString: pic15,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-114",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-115",
        cellText: "",
        cellLocation: "item-image-cell5",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__16.png",
          imageString: pic16,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-115",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-116",
        cellText: "",
        cellLocation: "item-image-cell6",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__17.png",
          imageString: pic17,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-116",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-117",
        cellText: "",
        cellLocation: "item-image-cell7",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__18.png",
          imageString: pic18,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-117",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-118",
        cellText: "",
        cellLocation: "item-image-cell8",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__19.png",
          imageString: pic19,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-118",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
      {
        id: "target-119",
        cellText: "",
        cellLocation: "item-image-cell9",
        cellStyle: "myBoxP",
        image: {
          type: "IMAGE",
          draggable: true,
          imageId: "Picture__20.png",
          imageString: pic20,
          imageUrl: "img/Beagle1.png",
          currentImgDivId: "target-119",
          dropImgLoc: "",
          dropImgParent: "parentContainer11",
        },
      },
    ],
  },
];

export const emptyRow = {
  id: "row101",
  cellArray: [
    {
      id: "label-100",
      cellText: "Label100",
      cellLocation: "item-label-cell100",
      cellStyle: "myLabelBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "",
      },
    },
    {
      id: "target-00",
      cellText: "",
      cellLocation: "item-image-cell0",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-01",
      cellText: "",
      cellLocation: "item-image-cell1",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-02",
      cellText: "",
      cellLocation: "item-image-cell2",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-03",
      cellText: "",
      cellLocation: "item-image-cell3",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-04",
      cellText: "",
      cellLocation: "item-image-cell4",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-05",
      cellText: "",
      cellLocation: "item-image-cell5",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-06",
      cellText: "",
      cellLocation: "item-image-cell6",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-07",
      cellText: "",
      cellLocation: "item-image-cell7",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-08",
      cellText: "",
      cellLocation: "item-image-cell8",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
    {
      id: "target-09",
      cellText: "",
      cellLocation: "item-image-cell9",
      cellStyle: "myBox",
      image: {
        type: "",
        draggable: false,
        imageId: "",
        imageUrl: "",
        currentImgLoc: "",
        dropImgLoc: "",
        dropImgParent: "parentContainer0",
      },
    },
  ],
};

export default INITIALGRID;
